// This file is automatically generated by VS Code
// Please do not modify it manually. All changes will be lost.
var React = require('/Users/rico/projects/ricokareem/bioenergetics3/node_modules/react');
var { Component } = React;
var ReactNative = require('/Users/rico/projects/ricokareem/bioenergetics3/node_modules/react-native');
var { AppRegistry } = ReactNative;
AppRegistry.registerRunnable('main', function(appParameters) {
    AppRegistry.runApplication('bioenergetics3', appParameters);
});
require('/Users/rico/projects/ricokareem/bioenergetics3/index.js');